version: '3'
services:

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: realworld
      POSTGRES_USER: realworld
      POSTGRES_PASSWORD: realworld
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    image: touk/kotlin-spring-realworld:$TAG
    build:
      context: ../
      dockerfile: docker/app.Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/realworld
      SPRING_DATASOURCE_USERNAME: realworld
      SPRING_DATASOURCE_PASSWORD: realworld
    depends_on:
      - db
    command: ["/tools/wait-for-it.sh", "db:5432", "-t", "30", "--", "./run-app.sh"]

  acceptance_tests:
    image: touk/realworld-acceptance-tests:$TAG
    build:
      context: ../
      dockerfile: docker/acceptance.Dockerfile
    environment:
      APIURL: http://app:8080
    depends_on:
      - app
    volumes:
      - ../acceptance/newman:/acceptance/newman
    command: ["/tools/wait-for-it.sh", "app:8080", "-t", "30", "--", "./run-api-tests.sh"]

volumes:
  db-data:
